#!/usr/bin/env bash
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/functions"

APP="$1"
for SERVICE in "$PLUGIN_DATA_ROOT"/*; do
    DATABASES="$(ls -lAh $SERVICE/dbs/ | grep '^d' | awk '{print $9}')"
    for DB in $DATABASES; do
        remove_from_links_file "$(basename "$SERVICE")" "$APP" "$DB"
    done
done
exit 0
