#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

mysql-connect-cmd() {
  declare desc="connect via mysql to a $PLUGIN_SERVICE service"
  local cmd="$PLUGIN_COMMAND_PREFIX:connect" argv=("$@"); [[ ${argv[0]} == "$cmd" ]] && shift 1
  declare SERVICE="$1"
  declare DATABASE="$2"

  [[ -z "$SERVICE" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$DATABASE" ]] && dokku_log_fail "Please specify a name for the database"
  verify_service_name "$SERVICE"
  SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  SERVICE_NAME="$(get_service_name "$SERVICE")"
  if [[ ! -d "$SERVICE_ROOT/dbs/$DATABASE/" ]]; then
    dokku_log_fail "Database $DATABASE is not configured!"
  fi
  USER="$(cat "$SERVICE_ROOT/dbs/$DATABASE/USER")"
  PASSWORD="$(cat "$SERVICE_ROOT/dbs/$DATABASE/PASSWORD")"
  has_tty && SERVICE_TTY_OPTS="-t"

  docker exec -i $SERVICE_TTY_OPTS "$SERVICE_NAME" mysql --user=$USER --password="$PASSWORD" --database="$DATABASE"
}

mysql-connect-cmd "$@"
